server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8081/
          predicates:
            - Path=/users/**
        - id: friends
          uri: http://localhost:8082/
          predicates:
            - Path=/friends/**
        - id: chat
          uri: http://localhost:8083/
          predicates:
            - Path=/chat/**
        - id: notification
          uri: http://localhost:8084/
          predicates:
            - Path=/notification/**
        - id: file
          uri: http://localhost:8086/
          predicates:
            - Path=/file/**
